### ISSUE TITLE
Unhandled Exception: System.InvalidOperationException: 

### ISSUE THREAD

**Issue by B0R1K** [Seddryck/RsPackage#17]
Hi there, i keep getting following error: 

Unhandled Exception: System.InvalidOperationException: Operation is not valid du
e to the current state of the object.
   at RsPackage.StreamProvider.FileStreamProvider.OnError(String message) in C:\
projects\rspackage\RsPackage\StreamProvider\FileStreamProvider.cs:line 82
   at RsPackage.StreamProvider.FileStreamProvider.GetBytes(String path) in C:\pr
ojects\rspackage\RsPackage\StreamProvider\FileStreamProvider.cs:line 40
   at RsPackage.Execution.CatalogItemService.Create(String name, String parent,
String path, String description, Boolean hidden) in C:\projects\rspackage\RsPack
age\Execution\CatalogItemService.cs:line 36
   at RsPackage.Execution.ReportService.Create(String name, String parent, Strin
g path, String description, Boolean hidden, IDictionary`2 dataSources, IDictiona
ry`2 sharedDatasets) in C:\projects\rspackage\RsPackage\Execution\ReportService.
cs:line 26
   at RsPackage.Parser.Xml.ReportParser.Execute(XmlNode node) in C:\projects\rsp
ackage\RsPackage\Parser\Xml\ReportParser.cs:line 60
   at RsPackage.Parser.Xml.FolderParser.Execute(XmlNode node) in C:\projects\rsp
ackage\RsPackage\Parser\Xml\FolderParser.cs:line 46
   at RsPackage.Parser.Xml.FolderParser.Execute(XmlNode node) in C:\projects\rsp
ackage\RsPackage\Parser\Xml\FolderParser.cs:line 51
   at RsPackage.Action.Publisher.Execute(MemoryStream stream) in C:\projects\rsp
ackage\RsPackage\Action\Publisher.cs:line 66
   at RsPackage.Action.Publisher.Execute() in C:\projects\rspackage\RsPackage\Ac
tion\Publisher.cs:line 40
   at RsPackage.Program.Publish(PublishOptions options) in C:\projects\rspackage
\RsPackage\Program.cs:line 39
   at RsPackage.Program.<>c.<Main>b__0_0(PublishOptions o) in C:\projects\rspack
age\RsPackage\Program.cs:line 22
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,TResult](ParserResult`1
 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 notParsedFunc)
   at RsPackage.Program.Main(String[] args) in C:\projects\rspackage\RsPackage\P
rogram.cs:line 21

Thank you for your help.

Are you still working on this project ?

Thanks again...

Borik

**Comment by Seddryck** [comment]
Thx for feedback, I'll take a look within the next days. 

This project deserves much more time that I had previous months but I should be back on it next month. 

Feel free to share your feedback, will take it into account.

**Comment by B0R1K** [comment]
Ok i got pass this, i had to start path with "/", 
```xml
<Report Name="report">
	<Path>/Reprot.rdl</Path>			                   
</Report>
```

Next issue i am facing is 

The dataset `DataSource1' refers to the shared data source `DataSource1', which is not published on the report server.  The shared data source `DataSource1' must be published before this report can run.

```
The data source 'DataSource1' of the report 'AD' has not been re-assigned because this data source is not defined in the deployment manifest.
```

I have DataSource1 on Server, how do i specify it in deployment manifest?

Thank you.

Borik

**Comment by B0R1K** [comment]
Same thing for DataSources, requires "/"
```xml
<Folder Name="Data Sources">
   <DataSource Name="DataSource1">
      <Path>/DataSource1.rds</Path>
   </DataSource>
</Folder>
```

Also is there way to prevent overwrite ?

Borik

**Comment by Seddryck** [comment]
Need to check on another computer to confirm but I think you can specify the "/" in the argument ```-f```. :-)

As far as I remember, currently, nothing is deleted, we only create new files (and folders) if they are not existing and delete/recreate the existing files. But, referenced data sources must be in the manifest or it's not possible to re-assign them during the deployment.

I'd say that at the moment we "overload" more than we "override". The issue #13 is already enlisting a feature to consider "override" for security. It could also be a feature to consider "preserve" and only create non-existing file but avoiding to update an already existing file. Make sense?

**Comment by B0R1K** [comment]
my command line:
`c:\RS_test>RsPackage.exe publish -u http://ssrsserver/ReportServer_SQLEXPRESS/ -f / -s c:\RS_test\SubFolder.xml
`
and if i dont put "/" in path in SubFolder.xml for reports its crashes...  

yes "Preserve" make sense...

**Comment by Seddryck** [comment]
Oki sounds like a true bug for the slash.

Will add a feature for override and another for preserve.

**Comment by B0R1K** [comment]
Hi Seddryck, any word on when you will have time to add these features? 

Thank you

**Comment by Seddryck** [comment]
Surely in April.

**Comment by B0R1K** [comment]
I have added an overwrite to DataSource, and i am realizing now that would be a good to have one for all as well..

If you like the current change that in pull request, i will make similar to others as well.

**Comment by Seddryck** [comment]
I merged but changed the default value to true (when attribute ```overwrite``` is not specified).

I think that this attribute is useful at the datasource level but for the reports I think it'd be more useful to have it in the command line than in the XML.

**Comment by B0R1K** [comment]
How would the syntax for Reports to keep/or overwrite look like in command line?

Also for DataSet it might make sense to have overwrite in XML as well?

**Comment by B0R1K** [comment]
Also Error i reported about path was due to me using an older nuget version of Project, i think you fixed it since then... 

Also added another pull request...

**Comment by Seddryck** [comment]
This become a really messy issue. Will close it an answer to your question at #22
